version: '3'


services:
  postgres:
    image: postgres
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata/postgres:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/1-schema.sql
#      - data.sql:/docker-entrypoint-initdb.d/2-data.sql # Data de test
    restart: always
    networks:
      - default
  mongo:
    image: mongo:3.4
    env_file:
      - .env
    ports:
      - "27017:27017"
    restart: always
    networks:
      - default
  api:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "8080:8080"
    restart: always